### ISSUE TITLE
第四周第一次更新总结

### ISSUE THREAD

**Issue by icecity96** [icecity96/HIT-Friends-Social-Analysis#3]
- 密码加密，采用MD5方式，测试方法调用`PassWord.md5encode` 传入要加密的字符串，输出加密后的字符串，可在http://www.md5.cz 上测试加密后的字符串是否正确
- 密码格式校验，采用正则方式，测试方法调用`PassWord.isLegitimate`传入密码明文，返回明文密码是否符合格式。合法格式见方法的`javadoc`
- 默认头像自动生成，测试方法调用`FontImgUtil.createImage(String str, String imgName)`,该方法尚存在缺陷如下：1.图片生成位置尚未确定，需组内协调(个人测试用的是`/tmp/'目录，windows用户请修改`FontImgUtil.DEFAULT_IMAGE_PATH`值）2.生成的图片不是很细腻，尚不知解决方法
- 获取用户昵称的首字母(首字)，测试方法调用`StringUtil.getCharString` 返回首字母(首字)
- 完成业务层，用户登录，注册，用户是否存在判断功能，但尚未连上数据库测试，等待数据库方面完成相关内容。
- 完成Control层，登录功能，尚未与前端连接测试。

**Comment by ghost** [comment]
登录界面版本一：实现登录注册界面之间切换；整体界面位于中间位置；后背景完全填充；实现Remember me选项。
登录界面版本二：在版本一的基础上实现账号密码错误时展示警告。
登录界面版本二：在版本二的基础上将登录注册界面整体右移，在左侧添加weblogo以及web介绍等内容；但是界面切换出现问题，尚未解决；页面布局有待完善。

**Comment by XiaoGA0914** [comment]
登录界面版本一：实现登录注册界面之间切换；整体界面位于中间位置；后背景完全填充；实现Remember me选项。
登录界面版本二：在版本一的基础上实现账号密码错误时展示警告。
登录界面版本二：在版本二的基础上将登录注册界面整体右移，在左侧添加weblogo以及web介绍等内容；但是界面切换出现问题，尚未解决；页面布局有待完善。

**Comment by LiuXiaoCN** [comment]
已解决：
  1.完成mybatis配置。基本实现dao层以及po持久化对象的基本代码，以及dao和po接口的xml映射。 
  2.完成初始登录界面在mysql中的表的设计，并且与po形成映射。
尚未解决：
  1.未完成合并，因此不知效果。
  2.因代码不完全以及技术原因，因此暂未测试，于下次提交前解决。

**Comment by icecity96** [comment]
@LiuXiaoCN XML文件应当放在src/main/resource目录下，另外注意数据库里数据类型和User类里面数据类型相对应。mybatis 内配置数据库本地时用户不要使用root(每个人root密码不同)，可统一创建一个新用户如hfsa，密码为空，方便其余成员使用。
