### ISSUE TITLE
第五周第一次更新总结

### ISSUE THREAD

**Issue by icecity96** [icecity96/HIT-Friends-Social-Analysis#5]
- 完成新浪博客的爬虫编写(没有反扒网站的爬虫基本已经完成)
- 新浪微博爬取失败，由于微博存在反爬取，争取本周内解决改问题

@XiaoGA0914 @LiuXiaoCN  请及时更新总结！！

**Comment by ghost** [comment]
1. 准备开展HomePage.jsp界面开发
2. 优化Login.jsp界面

**Comment by LiuXiaoCN** [comment]
对于mybatis的configuration的改进。现在基本能使用。后续将进行代码的改进，用注解的方式写新代码。
