### ISSUE TITLE
第六周第一次更新总结

### ISSUE THREAD

**Issue by icecity96** [icecity96/HIT-Friends-Social-Analysis#8]
- 微博API学习，完成微博后台授权，微博提取，重构登陆注册后台功能
- 本周第二次更新时要将已完成部分前端后台数据库连接(登录注册）

**Comment by ghost** [comment]
更新配置结构、主界面设计基本确定，本周末基本实现主界面布局，后期将完善细节

**Comment by LiuXiaoCN** [comment]
用户dao层接口用注解方式完成。新需求：需要建立AccessToken表以及Statues微博信息表，初步决定在微博表中使用微博id、内容、回复者id、评论数和转发数为基本属性，之后讨论后决定具体情况。由于对accesstoken和status理解较浅，因此authorzedao中的接口注释自己也不太清楚正确与否，将在下一次提交时解决，使功能能基本实现。
